### ISSUE TITLE
FLOSS, Kibi ahd Current Licensing

### ISSUE THREAD

**Issue by chlarsen** [sirensolutions/kibi#100]
Greetings from Malawi,
This is Kibi-specific and does not fit into the Elastic discussion forum.
Could you kindly confirm that Kibi is, except for development snapshots, not free/libre open-source software any more (FLOSS)?
I require Elastic with Kibana or Kibi for a production environment in least developed countries and have to absolutely clear about the long-term security in terms of FLOSS and licensing costs.
Your kind assistance is highly appreciated.
Chris

**Comment by jccq** [comment]
Hi Chris

The code you see is licenced Apache but it's just (part ) of the frontend .
We do this so that if kibana wants to take part of the code and improve the
base project they're free to do so. (And also for those writing
integrations and extensions )

The full siren platform (formerly kibi) requires also the backend (the
elasticsearch plugin and others ) which are now commercially licenced
therefore siren as a whole is not floss now, but rather commercial
"freemium" (A free 1 node siren  licence is available from the download
portal)

For more pricing info contact us through the site best!

**Comment by chlarsen** [comment]
Thank you, Giovanni, for this clarification.
When you said that the backend (Elasticsearch plugin and others) are now commercially liucensed, I assume you mean the interface between the frontend and Elasticsearch, not Elasticsearch itself? I understand that Elasticsearch is FLOSS, correct?
Thank you and have a great weekend,
Chris


On Friday, January 26, 2018 20:58 CAT, Giovanni Tummarello <notifications@github.com> wrote:
 Hi Chris

The code you see is licenced Apache but it's just (part ) of the frontend .
We do this so that if kibana wants to take part of the code and improve the
base project they're free to do so. (And also for those writing
integrations and extensions )

The full siren platform (formerly kibi) requires also the backend (the
elasticsearch plugin and others ) which are now commercially licenced
therefore siren as a whole is not floss now, but rather commercial
"freemium" (A free 1 node siren licence is available from the download
portal)

For more pricing info contact us through the site best!

**Comment by jccq** [comment]
Yes .. Siren requires the Federate plugin for elasticsearch (formerly
"vanguard" plugin ) to operate which is under a commercial model
Best!

On 26 Jan 2018 14:13, "Christoph H. Larsen" <notifications@github.com>
wrote:


Thank you, Giovanni, for this clarification.
When you said that the backend (Elasticsearch plugin and others) are now
commercially liucensed, I assume you mean the interface between the
frontend and Elasticsearch, not Elasticsearch itself? I understand that
Elasticsearch is FLOSS, correct?
Thank you and have a great weekend,
Chris



On Friday, January 26, 2018 20:58 CAT, Giovanni Tummarello <
notifications@github.com> wrote:
 Hi Chris

The code you see is licenced Apache but it's just (part ) of the frontend .
We do this so that if kibana wants to take part of the code and improve the
base project they're free to do so. (And also for those writing
integrations and extensions )

The full siren platform (formerly kibi) requires also the backend (the
elasticsearch plugin and others ) which are now commercially licenced
therefore siren as a whole is not floss now, but rather commercial
"freemium" (A free 1 node siren licence is available from the download
portal)

For more pricing info contact us through the site best!
—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--
Dr Christoph H. Larsen
synaLinQ
296/33 Lương Định Của, Ngọc Hội 2, Vĩnh Ngọc
Nha Trang, Khánh Hòa, Việt Nam
Mobile: +84-98-9607357 <+84%2098%20960%2073%2057> (Vietnam)
        +254-701-279511 <+254%20701%20279511> (Kenya)
        +265-998-393993 <+265%20998%2039%2039%2093> (Malawi)
        +49-176-96456254 <+49%20176%2096456254> (Germany)
Fax: +49-231-292734790 <+49%20231%20292734790>
E-mail: christoph.larsen@synalinq.com
Skype: christoph.larsen

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sirensolutions/kibi/issues/100#issuecomment-360877369>,
or mute the thread

**Comment by chlarsen** [comment]
Thank you, Giovanni, that makes it very clear. Have a good weekend!
Chris


On Friday, January 26, 2018 22:17 CAT, Giovanni Tummarello <notifications@github.com> wrote:
 Yes .. Siren requires the Federate plugin for elasticsearch (formerly
"vanguard" plugin ) to operate which is under a commercial model
Best!

On 26 Jan 2018 14:13, "Christoph H. Larsen" <notifications@github.com>
wrote:


Thank you, Giovanni, for this clarification.
When you said that the backend (Elasticsearch plugin and others) are now
commercially liucensed, I assume you mean the interface between the
frontend and Elasticsearch, not Elasticsearch itself? I understand that
Elasticsearch is FLOSS, correct?
Thank you and have a great weekend,
Chris



On Friday, January 26, 2018 20:58 CAT, Giovanni Tummarello <
notifications@github.com> wrote:
Hi Chris

The code you see is licenced Apache but it's just (part ) of the frontend .
We do this so that if kibana wants to take part of the code and improve the
base project they're free to do so. (And also for those writing
integrations and extensions )

The full siren platform (formerly kibi) requires also the backend (the
elasticsearch plugin and others ) which are now commercially licenced
therefore siren as a whole is not floss now, but rather commercial
"freemium" (A free 1 node siren licence is available from the download
portal)

For more pricing info contact us through the site best!
