### ISSUE TITLE
Query on Oracle database fails

### ISSUE THREAD

**Issue by bartverweire** [sirensolutions/kibi#56]
### Versions

Kibi: 4.5.3

Operating System: Windows 7
### Behavior

When I create a simple query :
select x from dual

I get an error in the interface
TypeError: Cannot read property 'message' of null
    at formatMsg (http://localhost:5606/bundles/commons.bundle.js?v=12068:64395:77)
    at Notifier.error (http://localhost:5606/bundles/commons.bundle.js?v=12068:64217:17)
    at wrapper (http://localhost:5606/bundles/commons.bundle.js?v=12068:8620:20)
    at processQueue (http://localhost:5606/bundles/commons.bundle.js?v=12068:42487:29)
    at http://localhost:5606/bundles/commons.bundle.js?v=12068:42503:28
    at Scope.$eval (http://localhost:5606/bundles/commons.bundle.js?v=12068:43747:29)
    at Scope.$digest (http://localhost:5606/bundles/commons.bundle.js?v=12068:43565:32)
    at Scope.$apply (http://localhost:5606/bundles/commons.bundle.js?v=12068:43855:25)
    at done (http://localhost:5606/bundles/commons.bundle.js?v=12068:38284:48)
    at completeRequest (http://localhost:5606/bundles/commons.bundle.js?v=12068:38482:8)

and kibi crashes, with message:
            resultset.toObjArray(function (err, results) {
                     ^

TypeError: Cannot read property 'toObjArray' of undefined
    at C:\DevEnv\kibi-4.5.3-windows64\src\plugins\kibi_core\lib\queries\jdbc_query.js:94:22
    at C:\DevEnv\kibi-4.5.3-windows64\node_modules\jdbc\lib\statement.js:50:16
#### Expected:

Query should return 1 column, contianing 'X'
#### Actual:

Error message + crash
### Steps to reproduce the problem

I have created an Oracle datasource 
jdbc:oracle:thin:@<hostname>:<port>/<service_name>
libraries path : C:\ORACLE\11.2.0.4\jdbc\lib
driver name oracle.jdbc.OracleDriver
libraries : ojdbc6.jar

The sample query should work with any oracle database.

**Comment by scampi** [comment]
This is fixed with the latest release https://github.com/sirensolutions/kibi/releases/tag/tag-4.5.3-1

**Comment by hcountou** [comment]
Hello,

I'm having a lot of fun with Kibi and ES. I appreciate the new release of your official docker images, so i try it on.
And guess what ? Still amazing !

But a new user came to me and asked if we could try to build some dashboards with Kibi on some data located in an oracle DB. I said yes but maybe too fast...

As i follow your advices for _bartverweire_ on getting Kibi able to recognize the Oracle connexion, i set : kibi_core.load_jdbc: true
...by adding this line into my kibi.yml file as suggested.
And i restart Kibi.
Everything is ok.

Then i tried to add a new datasource but when i saved it, Kibi tells me to turn that option (above) to "true".
I checked in  "/opt/kibi/config/kibi.yml" and it seems fine.

I'm using :
sirensolutions/kibi-community-demo-full:4.5.4

And everything is working appart from that.

This "oracle" option should be listed into the loaded modules of Kibi, am i right ?
If you can help or give me some advices, it would be great. Thanks in advance.

**Comment by jccq** [comment]
@hcountou beside the specific issues (i leave @scampi to comment) pls consider you need to ETL the data from oracle into an Elasticsearch table in the current version of Kibi for Kibi to use it with the full join/widgets capabilities. 

Direct datasources are (currently) used just for "filters" e.g. see our distribution demo where we have a list of articles and a SQL query that selects the "top 50 companies". Thansk to our "external query" aggregator one can then see just the articles that are about the "top 50 companies".  but one would be able to have a dashboard dedicated to the "top 50 companies"without a Logstash configuration that transforms that SQL query into an index (not a complex thing to do per se..)

**Comment by hcountou** [comment]
Hello,

Alright, i understand that if you want to do some relational queries you need to have your data in ES (using Logstash or any other index generator). 

But the point is that i want also to enrich our data on the endpoint.

Example, if you have a Kibi relational dashboards set, i want to set a companion table linked the dashboard connected to an external datasource.

By using : 
"Special variables @doc[_source][property_name]@ will be replaced by values extracted from the documents matching the current selection "

I though i could provide a parameter from the relational dashboard to the external datasource query and then to the associated table in the dashboard.

What i know is to set :
- relational panels & dashboards
- queries to external datasources (not oracle) such as REST datasources

Tell me if i see it wrong. But that's the idea.

Thanks.

**Comment by jccq** [comment]
Possibly :)

An example of usage (That would work):

Lets say that you have a list of customers in ES

but you dont have the transactions in ES, they are instead on a REST
service or on a ORACLE database

then yes you could configure the datasource so that when you click on a
customer it will display the last 10 transactions of that customer in the
Kibi template viewer component.

Alternatively lets say you have a list of transactions but you dont have
the user details and you want to show them when one clicks on a
transaction, that is equally doable.

this is similar to what happens in our distribution demo, if you click on a
company you see the list of "companies in the same domain" that widget is
pulling data from SQL.

hope you get it working, if you're having problems let us know and we can
certainly help.

**Comment by hcountou** [comment]
That's encouraging ! Then all i have to do is to set my external datasouces links.

One for a Postgres DB is fine (i get a very nice table)
One for SPARQL over http is ok
One for a REST API service is fine because the API provides json...but the other REST API service, we had to change it in order to receive json messages.

(Actually Kibi only works with json for external sources as mentionned her : https://docs.siren.solutions/kibi/community/4.5.4/#external_datasources)

But i can not have this Oracle SQL conn because, even after the changes in kibi.yml, it seams that kibi is not loading it.

I put my drivers in the "/tmp" folder. Do you think i should put ther into "/opt/drivers" ? I'll try.

How to check that Kibi is having the jdbc parameter correctly set ?
I went into my docker and saw the line uncommented in the kibi.yml file. But not on the web side.

**Comment by scampi** [comment]
Do you have anything in the logs ?

**Comment by scampi** [comment]
At the moment, the only to check if everything is correct is to run a simple query from the UI (in the `settings / queries` tab)

**Comment by hcountou** [comment]
None of my tests made it so far.

# To summarize

- the path you give in the [dockerhub](https://hub.docker.com/r/sirensolutions/kibi-community-standalone/) doesn't seems to be the right. I had to modify the file "/opt/kibi/kibi/config/kibi.yml" instead of "/opt/kibi/config/kibi.yml" for the modifications to be taken in consideration.

- then i've put my ojdbc jar into a "/opt/drivers" folder (that i create)  with the correct read options and set it to the kibi owner
- I restart the docker container and so Kibi...but then Kibi says : "plugin:kibi_core 	Query engine initialization failed", as in the following post (https://github.com/sirensolutions/kibi/issues/33)
- So i did as suggested : "apt-get install libstdc++6" but that was already installed properly.

#  My logs
In the log (Docker logs the kibi image), i have only 1 message a little bit strange (i don't think it's related) :
2016-12-23 16:09:39,127 INFO stopped: kibi (terminated by SIGTERM)
/usr/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '

# Kibi configuration
After having tried to set "load_jdbc: true" and failed, i've changed Kibi.yml configuration to this one, but i don't think there are any differences :

kibi_core:
  #load_jdbc: true
  datasource_encryption_algorithm: 'AES-GCM'
  datasource_encryption_key: 'iSxvZRYisyUW33FreTBSyJJ34KpEquWznUPDvn+ka14='
  datasource_cache_size: 501
  default_dashboard_id: Articles

#Add by me
kibi_core.load_jdbc: true

Any clue ?
How to look for the logs of kibi from inside the container ?
Does we have a proper command to restart Kibi instead of restarting the container ?
I tried : "/opt/kibi/kibi/bin/kibi serve stop/start" but it fails.
Does someone have any docker image with a jdbc jar enable ? It would be simple.

**Comment by hcountou** [comment]
And my kibi version is 4.5.4 in order to be compatible with siren join ( sirensolutions/kibi-community-demo-full:4.5.4)
So i pick up the docker from this adress :
https://support.siren.solutions/support/solutions/articles/17000034081-kibi-4-5-4-community-edition

**Comment by hcountou** [comment]
And the jdbc jar that i tried to load is : ojdbc6.jar that i retrieve from the oracle official site.

Thanks for your advices

**Comment by hcountou** [comment]
Ok i made some progress...

# Changing the Logs writing
I did not find any log other than the container log, so i changed the kibi.yml file for the logs :
"# If you would like to send the log output to a file you can set the path below.
logging.dest: /opt/kibi/logs/kibi_logs"

# Identifying the Error
After restarting the container (./bin/kibi stop/start does not work), i had access to my logs.
And like in [this post](https://groups.google.com/a/siren.solutions/forum/#!topic/kibi-users/u1gmtsvZFLM), i found a problem with the "libjvm.so" thing :
"object file: No such file or directory","name":"Error","stack":"Error: libjvm.so: cannot open shared "

# JAVA_HOME & LD_LIBRARY_PATH
echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64/jre

But nothing for $LD_LIBRARY_PATH...
Should i set it ?

**Comment by hcountou** [comment]
# $LD_LIBRARY_PATH
Ok i tried to set $LD_LIBRARY_PATH for both the root and the kibi user by defining it into them ".bashrc" files

$JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64/jre/
$LD_LIBRARY_PATH  = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server

# Finding the so called missing "libjvm.so"
"find / -type f -name libjvm.so 
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so"

# Kibi Logs (after reboot)
Message in the log still says :
["error","kibi_core"],"pid":7,"level":"error","message":"libjvm.so: cannot open shared object file: No such file or directory"

Any clue ?

**Comment by hcountou** [comment]
NB : if disable the "kibi_core.load_jdbc: true" option, the server is up & running

**Comment by Shreyanshupare** [comment]
Hi,
When i changes  "load_jdbc: true"   when i run the kibi it is showing Error:-
   kibi_core] Error: The specified module could not be found.

and in dashboard:-
kibi_core	1.0.0	 Query engine initialization failed

How to solve this error can you please suggest me .
I am using elasticsearch-2.4.1 and kibi-community-demo-full-4.6.4-2-windows64.
