### ISSUE TITLE
TypeError: jQuery(...).qtip is not a function

### ISSUE THREAD

**Issue by xycloud** [sirensolutions/kibi#85]
kibi master: 5.3.2
angular.js:12520 TypeError: jQuery(...).qtip is not a function
    at JoinExplanationHelper.initQtip (eval at <anonymous> (kibana.bundle.js?v=8467:1540), <anonymous>:98:25)

its ok in kibi-5.2.2 beta-1, but error in kibi master, could you give some help?

**Comment by szydan** [comment]
Hi @xycloud  we've just released 5.4.0-beta-2
https://github.com/sirensolutions/kibi/releases/tag/tag-5.4.0-beta-2
Master branch was also synced 

If the version is not a problem could you try one more time on this version 
We had similar issues before and usually, it is related to 2 version of jQuery being bundled by webpack.
Once you try on 5.4.0-beta-2 let us know, if the problem is still there we will investigate

**Comment by xycloud** [comment]
still got this erorr. any possible reason about this?

**Comment by szydan** [comment]
Could you describe how to reproduce this error, please?
Also, are you running Kibi from 5.4.0-beta-2 or master?

**Comment by xycloud** [comment]
as we know, the relation filter should have a different tooltip if everything is ok. but 5.4.0 doesn't, we can see the error message in browser console

**Comment by szydan** [comment]
@xycloud I've just tried on my installation and I can not see it 
Could tell me which browser you are using and which OS.
Also, could you confirm that you get an error by simply hovering over the filter as I'm doing?
![out](https://user-images.githubusercontent.com/900118/28683484-a9574fce-72f8-11e7-9a0e-04848009555b.gif)
