### ISSUE TITLE
5.6.4 support, to accomodate Elasticsearch "StackOverflowError after a Fatal Error on Network Layer" bug

### ISSUE THREAD

**Issue by HandsomeWins** [sirensolutions/kibi#97]
**Kibi version**: 5.6.3

**Elasticsearch version**: 5.6.4

**Describe the feature**:

Hello, 

Please support Elasticsearch release 5.6.4. 5.6.3 suffers from a bug that causes Elasticsearch nodes to crash due to "StackOverflowError after a Fatal Error on Network Layer" when certain kinds of (or too many?) search requests hit cluster nodes. This affected me in particular just due to 5 machine learning jobs querying the cluster for data. 

https://github.com/elastic/elasticsearch/issues/27184

I saw that Siren Kibi/Vanguard now supported the latest 5.6.3, so I upgraded my cluster to take advantage of latest bug fixes/enhancements, and suffered lots of cluster issues because of it. 

The jump to 5.6.4 is small in terms of changes, if you guys could support the newer release then I can evaluate Siren Kibi/Vanguard. 

Thanks!

**Comment by szydan** [comment]
Hi @HandsomeWins we are currently working to sync to 5.6.4
Once we will release Vanguard 5.6.4 the Kibi master will be synced too
Stay tuned

**Comment by jccq** [comment]
Was wondering how many nodes do you have ? Is it X pack learning or
something else?

On 13 Nov 2017 19:43, "Peter Wins" <notifications@github.com> wrote:

*Kibi version*: 5.6.3

*Elasticsearch version*: 5.6.4

*Describe the feature*:

Hello,

Please support Elasticsearch release 5.6.4. 5.6.3 suffers from a bug that
causes Elasticsearch nodes to crash due to "StackOverflowError after a
Fatal Error on Network Layer" when certain kinds of (or too many?) search
requests hit cluster nodes. This affected me in particular just due to 5
machine learning jobs querying the cluster for data.

elastic/elasticsearch#27184
<https://github.com/elastic/elasticsearch/issues/27184>

I saw that Siren Kibi/Vanguard now supported the latest 5.6.3, so I
upgraded my cluster to take advantage of latest bug fixes/enhancements, and
suffered lots of cluster issues because of it.

The jump to 5.6.4 is small in terms of changes, if you guys could support
the newer release then I can evaluate Siren Kibi/Vanguard.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sirensolutions/kibi/issues/97>, or mute the thread

**Comment by HandsomeWins** [comment]
Thanks! Looking forward to the 5.6.4 release. ~50 physical nodes in a cluster.

**Comment by szydan** [comment]
Hi @HandsomeWins 
We've just released Vanguard 5.6.4 which is compatible with Kibi 5.4.3-3
Please try it

**Comment by szydan** [comment]
@HandsomeWins also Kibi master is now synced to 5.6.4 
However, it will take some more time until it will become stable
Closing this issue, feel free to reopen if needed
